# Ultra Simple AAB Build - Avoiding Java Version Conflicts
# Uses React Native CLI approach instead of Capacitor

workflows:
  simple-aab:
    name: Simple React AAB Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.optibuy.collective"
        
    scripts:
      - name: Create Minimal Project
        script: |
          echo "=== Creating ultra-minimal Android project ==="
          
          # Create React Native project with minimal setup
          npx react-native init OptiBuy --template react-native-template-typescript
          cd OptiBuy
          
          # Create basic app content
          cat > App.tsx << 'EOF'
          import React from 'react';
          import {SafeAreaView, Text, StyleSheet, TouchableOpacity, Alert} from 'react-native';

          function App(): React.JSX.Element {
            return (
              <SafeAreaView style={styles.container}>
                <Text style={styles.title}>OptiBuy</Text>
                <Text style={styles.subtitle}>Collective Purchasing Platform</Text>
                <Text style={styles.description}>
                  Discover invisible buying neighbors for bulk discounts
                </Text>
                <TouchableOpacity 
                  style={styles.button}
                  onPress={() => Alert.alert('Welcome', 'Welcome to OptiBuy!')}
                >
                  <Text style={styles.buttonText}>Get Started</Text>
                </TouchableOpacity>
              </SafeAreaView>
            );
          }

          const styles = StyleSheet.create({
            container: {
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: '#f5f5f5',
              padding: 20,
            },
            title: {
              fontSize: 32,
              fontWeight: 'bold',
              color: '#333',
              marginBottom: 10,
            },
            subtitle: {
              fontSize: 18,
              color: '#666',
              marginBottom: 20,
            },
            description: {
              fontSize: 16,
              color: '#888',
              textAlign: 'center',
              marginBottom: 30,
            },
            button: {
              backgroundColor: '#007AFF',
              paddingHorizontal: 30,
              paddingVertical: 15,
              borderRadius: 8,
            },
            buttonText: {
              color: 'white',
              fontSize: 18,
              fontWeight: '600',
            },
          });

          export default App;
          EOF

      - name: Setup Android Build
        script: |
          cd OptiBuy
          
          echo "=== Setting up Android build with Java 17 ==="
          
          # Update package name in Android config
          sed -i 's/com.optibuy/com.optibuy.collective/g' android/app/build.gradle
          sed -i 's/com.optibuy/com.optibuy.collective/g' android/app/src/main/AndroidManifest.xml
          
          # Force Java 17 in all gradle files
          find android -name "build.gradle" -exec sed -i 's/JavaVersion.VERSION_.*)/JavaVersion.VERSION_17)/g' {} \;
          find android -name "build.gradle" -exec sed -i 's/jvmTarget.*=.*/jvmTarget = "17"/g' {} \;
          
          # Set gradle properties
          cat >> android/gradle.properties << 'EOF'
          org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
          EOF
          
          # Create keystore
          echo "=== Creating keystore ==="
          keytool -genkey -v -keystore android/app/optibuy.keystore -alias optibuy -keyalg RSA -keysize 2048 -validity 10000 -storepass anyque123 -keypass anyque123 -dname "CN=OptiBuy, O=OptiBuy, C=TR"
          
          # Configure signing
          cat >> android/app/build.gradle << 'EOF'

          android {
              signingConfigs {
                  release {
                      storeFile file('optibuy.keystore')
                      storePassword 'anyque123'
                      keyAlias 'optibuy'
                      keyPassword 'anyque123'
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                  }
              }
          }
          EOF

      - name: Build AAB
        script: |
          cd OptiBuy/android
          
          # Set Java 17 environment
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          
          echo "Java version:"
          java -version
          
          echo "=== Building AAB ==="
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease
          
          echo "=== Checking outputs ==="
          find . -name "*.aab" -exec ls -lh {} \;
          
          echo "=== Copying AAB ==="
          cp app/build/outputs/bundle/release/app-release.aab ../../optibuy.aab
          ls -lh ../../optibuy.aab

    artifacts:
      - optibuy.aab
