workflows:
  optibuy:
    name: OptiBuy - Key Properties Fix (Simple & Clean)
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.optibuy.collective"
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
        ANDROID_HOME: /usr/local/share/android-sdk
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    scripts:
      - name: Create Keystore (Google Play Registered)
        script: |
          echo "=== Creating Upload Keystore ==="
          
          # Generate stable keystore for Google Play upload key reset
          keytool -genkeypair \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 9125 \
            -keystore upload-keystore.jks \
            -dname "CN=OptiBuy Collective, OU=Mobile Apps, O=OptiBuy, L=Istanbul, ST=Istanbul, C=TR" \
            -storepass optibuy_upload_2025 \
            -keypass optibuy_upload_2025
          
          # Verify keystore
          echo "Verifying keystore SHA1 fingerprint:"
          keytool -list -v -keystore upload-keystore.jks -storepass optibuy_upload_2025 -alias upload | grep "SHA1"
          
          # Export PEM certificate for Google Play upload key reset request
          keytool -export -rfc \
            -keystore upload-keystore.jks \
            -alias upload \
            -storepass optibuy_upload_2025 \
            -file upload_certificate.pem
          
          echo "Upload certificate exported to: upload_certificate.pem"
          
      - name: Build Android App with key.properties
        script: |
          echo "=== Building Android App with key.properties Configuration ==="
          
          # Create Android project structure
          mkdir -p OptiBuy/android/app/src/main/java/com/optibuy/collective
          mkdir -p OptiBuy/android/app/src/main/res/values
          mkdir -p OptiBuy/android/app/src/main/res/layout
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-hdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-mdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xhdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xxhdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xxxhdpi
          mkdir -p OptiBuy/android/gradle/wrapper
          
          cd OptiBuy
          
          # Copy keystore to android/app directory
          cp ../upload-keystore.jks android/app/upload-keystore.jks
          
          # CREATE key.properties FILE (this is the fix!)
          cat > android/key.properties << 'EOF'
          storePassword=optibuy_upload_2025
          keyPassword=optibuy_upload_2025
          keyAlias=upload
          storeFile=upload-keystore.jks
          EOF
          
          echo "✅ key.properties file created"
          cat android/key.properties
          
          # Create gradle wrapper
          cat > android/gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          # Create gradle.properties (WITHOUT keystore info - that's in key.properties now!)
          cat > android/gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.enableJetifier=true
          android.bundle.enableUncompressedNativeLibs=false
          android.enableR8.fullMode=true
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          org.gradle.daemon=true
          EOF
          
          # Create settings.gradle
          cat > android/settings.gradle << 'EOF'
          rootProject.name = 'OptiBuy'
          include ':app'
          project(':app').projectDir = new File(rootProject.projectDir, 'app')
          EOF
          
          # Create root build.gradle
          cat > android/build.gradle << 'EOF'
          buildscript {
              ext {
                  buildToolsVersion = "34.0.0"
                  minSdkVersion = 21
                  compileSdkVersion = 35
                  targetSdkVersion = 35
              }
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.1.4'
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          EOF
          
          # CREATE app/build.gradle WITH key.properties LOADING (this is the critical fix!)
          cat > android/app/build.gradle << 'EOF'
          apply plugin: 'com.android.application'
          
          // LOAD key.properties FILE (this is what was missing!)
          def keystorePropertiesFile = rootProject.file("key.properties")
          def keystoreProperties = new Properties()
          if (keystorePropertiesFile.exists()) {
              keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
          }
          
          android {
              namespace 'com.optibuy.collective'
              compileSdkVersion rootProject.ext.compileSdkVersion
              buildToolsVersion rootProject.ext.buildToolsVersion
              
              defaultConfig {
                  applicationId "com.optibuy.collective"
                  minSdkVersion rootProject.ext.minSdkVersion
                  targetSdkVersion rootProject.ext.targetSdkVersion
                  versionCode 3
                  versionName "1.3.0"
              }
              
              signingConfigs {
                  debug {
                      storeFile file('debug.keystore')
                      storePassword 'android'
                      keyAlias 'androiddebugkey'
                      keyPassword 'android'
                  }
                  release {
                      // USE key.properties VALUES (this is the fix!)
                      if (keystorePropertiesFile.exists()) {
                          storeFile file(keystoreProperties['storeFile'])
                          storePassword keystoreProperties['storePassword']
                          keyAlias keystoreProperties['keyAlias']
                          keyPassword keystoreProperties['keyPassword']
                      }
                  }
              }
              
              buildTypes {
                  debug {
                      signingConfig signingConfigs.debug
                  }
                  release {
                      minifyEnabled true
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                      signingConfig signingConfigs.release
                  }
              }
              
              bundle {
                  language {
                      enableSplit = false
                  }
                  density {
                      enableSplit = true
                  }
                  abi {
                      enableSplit = true
                  }
              }
          }
          
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
              implementation 'com.google.android.material:material:1.9.0'
          }
          EOF
          
          # Create AndroidManifest.xml with Internet permission and cleartext traffic
          cat > android/app/src/main/AndroidManifest.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:theme="@style/AppTheme"
                  android:usesCleartextTraffic="true">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          
          # Create strings.xml
          cat > android/app/src/main/res/values/strings.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">OptiBuy</string>
          </resources>
          EOF
          
          # Create styles.xml
          cat > android/app/src/main/res/values/styles.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
                  <item name="colorPrimary">#4CAF50</item>
                  <item name="colorPrimaryDark">#388E3C</item>
                  <item name="colorAccent">#FF5722</item>
              </style>
          </resources>
          EOF
          
          # Create MainActivity.java with WebView loading Replit backend
          cat > android/app/src/main/java/com/optibuy/collective/MainActivity.java << 'EOF'
          package com.optibuy.collective;
          
          import androidx.appcompat.app.AppCompatActivity;
          import android.os.Bundle;
          import android.webkit.WebSettings;
          import android.webkit.WebView;
          import android.webkit.WebViewClient;
          
          public class MainActivity extends AppCompatActivity {
              private WebView webView;
              
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  
                  webView = new WebView(this);
                  setContentView(webView);
                  
                  WebSettings webSettings = webView.getSettings();
                  webSettings.setJavaScriptEnabled(true);
                  webSettings.setDomStorageEnabled(true);
                  webSettings.setLoadWithOverviewMode(true);
                  webSettings.setUseWideViewPort(true);
                  webSettings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
                  
                  webView.setWebViewClient(new WebViewClient());
                  
                  // Load OptiBuy backend from Replit
                  webView.loadUrl("https://opti-buy-tracker-metealper.replit.app");
              }
              
              @Override
              public void onBackPressed() {
                  if (webView.canGoBack()) {
                      webView.goBack();
                  } else {
                      super.onBackPressed();
                  }
              }
          }
          EOF
          
          # Create layout (not used since we're using WebView directly, but good to have)
          cat > android/app/src/main/res/layout/activity_main.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
          </FrameLayout>
          EOF
          
          # Create ProGuard rules
          cat > android/app/proguard-rules.pro << 'EOF'
          -keep class com.optibuy.collective.** { *; }
          -dontwarn okio.**
          -dontwarn retrofit2.**
          -keepattributes *Annotation*
          -keepattributes JavascriptInterface
          -keepclassmembers class * {
              @android.webkit.JavascriptInterface <methods>;
          }
          EOF
          
          # Create placeholder icons
          echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==' | base64 -d > android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==' | base64 -d > android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==' | base64 -d > android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==' | base64 -d > android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==' | base64 -d > android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          
          echo "✅ Android project created with key.properties configuration"
          
      - name: Build AAB with Gradle
        script: |
          echo "=== Building Android App Bundle (AAB) ==="
          cd OptiBuy/android
          
          echo "Verifying key.properties exists:"
          ls -la key.properties
          cat key.properties
          
          echo "Building AAB..."
          gradle clean
          gradle bundleRelease
          
          if [ -f "app/build/outputs/bundle/release/app-release.aab" ]; then
              cd ../..
              
              # Copy AAB to root
              cp OptiBuy/android/app/build/outputs/bundle/release/app-release.aab ./optibuy-v3-backend-connected.aab
              
              # Extract actual fingerprint from AAB
              mkdir -p verify_aab
              cd verify_aab
              unzip -q ../optibuy-v3-backend-connected.aab
              ACTUAL_SHA1=$(keytool -printcert -file META-INF/*.RSA 2>/dev/null | grep "SHA1:" | head -1 | awk '{print $2}')
              cd ..
              rm -rf verify_aab
              
              # Create deployment report
              echo "=== 🎉 AAB BUILD SUCCESSFUL ===" > deployment_report.txt
              echo "" >> deployment_report.txt
              echo "📦 AAB Details:" >> deployment_report.txt
              echo "   File: optibuy-v3-backend-connected.aab" >> deployment_report.txt
              echo "   Package: com.optibuy.collective" >> deployment_report.txt
              echo "   Version Code: 3" >> deployment_report.txt
              echo "   Version Name: 1.3.0" >> deployment_report.txt
              echo "   SHA1 Fingerprint: $ACTUAL_SHA1" >> deployment_report.txt
              echo "" >> deployment_report.txt
              echo "🔑 Upload Key Reset Required:" >> deployment_report.txt
              echo "   Expected by Google: 07:1A:D1:37:B9:6A:2B:12:F2:A4:F4:9D:42:BB:19:11:A3:EF:31:CD" >> deployment_report.txt
              echo "   Your AAB Fingerprint: $ACTUAL_SHA1" >> deployment_report.txt
              echo "" >> deployment_report.txt
              echo "📋 Next Steps:" >> deployment_report.txt
              echo "   1. Download: upload_certificate.pem" >> deployment_report.txt
              echo "   2. Go to: Google Play Console → Release → Setup → App signing" >> deployment_report.txt
              echo "   3. Click: 'Request upload key reset'" >> deployment_report.txt
              echo "   4. Upload: upload_certificate.pem" >> deployment_report.txt
              echo "   5. Wait: 48 hours for approval" >> deployment_report.txt
              echo "   6. Upload: optibuy-v3-backend-connected.aab" >> deployment_report.txt
              echo "" >> deployment_report.txt
              echo "✅ Backend Connection:" >> deployment_report.txt
              echo "   URL: https://opti-buy-tracker-metealper.replit.app" >> deployment_report.txt
              echo "   WebView: Enabled with JavaScript" >> deployment_report.txt
              echo "   Internet Permission: Granted" >> deployment_report.txt
              echo "   Cleartext Traffic: Enabled" >> deployment_report.txt
              
              echo ""
              echo "Build completed successfully!"
              ls -lh *.aab
              cat deployment_report.txt
          else
              echo "ERROR: AAB build failed"
              find OptiBuy/android -name "*.aab"
              exit 1
          fi
          
    artifacts:
      - "*.aab"
      - "*.pem"
      - "upload-keystore.jks"
      - "deployment_report.txt"
      - "OptiBuy/android/key.properties"
    publishing:
      email:
        recipients:
          - build@optibuy.com
        notify:
          success: true
          failure: true
