workflows:
  optibuy:
    name: OptiBuy React Native - Simple Working
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "com.optibuy.collective"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    scripts:
      - name: Create React Native Project Structure
        script: |
          echo "=== Creating React Native Project Structure ==="
          
          npm install -g @react-native-community/cli
          
          echo "Creating OptiBuy directory..."
          mkdir -p OptiBuy
          cd OptiBuy
          
          npm init -y
          
          mkdir -p android/app/src/main/java/com/optibuy/collective
          mkdir -p android/app/src/main/res/values
          mkdir -p android/app/src/main/assets
          mkdir -p android/gradle/wrapper
          
          echo "Creating package.json..."
          echo '{
            "name": "OptiBuy",
            "version": "1.2.0",
            "private": true,
            "scripts": {
              "android": "react-native run-android",
              "start": "react-native start"
            },
            "dependencies": {
              "react": "18.2.0",
              "react-native": "0.72.6"
            }
          }' > package.json
          
          echo "Creating app.json..."
          echo '{
            "name": "OptiBuy",
            "displayName": "OptiBuy"
          }' > app.json
          
          echo "Creating index.js..."
          echo "import {AppRegistry} from 'react-native';
          import App from './App';
          import {name as appName} from './app.json';
          
          AppRegistry.registerComponent(appName, () => App);" > index.js
          
          echo "Creating App.tsx..."
          echo "import React from 'react';
          import {SafeAreaView, Text, StyleSheet, View} from 'react-native';
          
          function App() {
            return (
              <SafeAreaView style={styles.container}>
                <View style={styles.content}>
                  <Text style={styles.title}>OptiBuy</Text>
                  <Text style={styles.subtitle}>Collective Purchasing Platform</Text>
                  <Text style={styles.description}>Ready for Google Play Store deployment</Text>
                </View>
              </SafeAreaView>
            );
          }
          
          const styles = StyleSheet.create({
            container: {
              flex: 1,
              backgroundColor: '#f8f9fa',
            },
            content: {
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              padding: 20,
            },
            title: {
              fontSize: 32,
              fontWeight: 'bold',
              marginBottom: 10,
              color: '#000',
            },
            subtitle: {
              fontSize: 18,
              marginBottom: 20,
              color: '#666',
            },
            description: {
              fontSize: 16,
              color: '#4CAF50',
              fontWeight: '600',
            },
          });
          
          export default App;" > App.tsx
          
          npm install
          
          echo "Directory structure created successfully"
          ls -la
          
      - name: Setup Android Configuration
        script: |
          echo "=== Setting up Android Configuration ==="
          cd OptiBuy
          
          echo "Creating Android gradle files..."
          
          echo 'rootProject.name = "OptiBuy"
          include ":app"
          
          project(":app").projectDir = new File(rootProject.projectDir, "app")' > android/settings.gradle
          
          echo 'distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists' > android/gradle/wrapper/gradle-wrapper.properties
          
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.enableJetifier=true
          android.bundle.enableUncompressedNativeLibs=false
          android.enableR8.fullMode=true
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          org.gradle.daemon=true
          MYAPP_UPLOAD_STORE_FILE=upload-keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=upload
          MYAPP_UPLOAD_STORE_PASSWORD=optibuy_upload_2025
          MYAPP_UPLOAD_KEY_PASSWORD=optibuy_upload_2025' > android/gradle.properties
          
          echo 'buildscript {
              ext {
                  buildToolsVersion = "34.0.0"
                  minSdkVersion = 21
                  compileSdkVersion = 35
                  targetSdkVersion = 35
                  ndkVersion = "21.4.7075529"
              }
              dependencies {
                  classpath("com.android.tools.build:gradle:8.1.4")
                  classpath("com.facebook.react:react-native-gradle-plugin")
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
                  maven { url "https://www.jitpack.io" }
              }
          }' > android/build.gradle
          
          echo 'apply plugin: "com.android.application"
          apply plugin: "com.facebook.react"
          
          react {
              entryFile = "index.js"
              enableHermes = true
              bundleInDebug = false
              bundleInRelease = true
          }
          
          android {
              ndkVersion rootProject.ext.ndkVersion
              compileSdkVersion rootProject.ext.compileSdkVersion
              
              namespace "com.optibuy.collective"
              defaultConfig {
                  applicationId "com.optibuy.collective"
                  minSdkVersion rootProject.ext.minSdkVersion
                  targetSdkVersion rootProject.ext.targetSdkVersion
                  versionCode 2
                  versionName "1.2.0"
              }
              
              signingConfigs {
                  debug {
                      storeFile file("debug.keystore")
                      storePassword "android"
                      keyAlias "androiddebugkey"
                      keyPassword "android"
                  }
                  release {
                      if (project.hasProperty("MYAPP_UPLOAD_STORE_FILE")) {
                          storeFile file(MYAPP_UPLOAD_STORE_FILE)
                          storePassword MYAPP_UPLOAD_STORE_PASSWORD
                          keyAlias MYAPP_UPLOAD_KEY_ALIAS
                          keyPassword MYAPP_UPLOAD_KEY_PASSWORD
                      }
                  }
              }
              
              buildTypes {
                  debug {
                      signingConfig signingConfigs.debug
                  }
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled true
                      proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
                  }
              }
              
              bundle {
                  language {
                      enableSplit = false
                  }
                  density {
                      enableSplit = true
                  }
                  abi {
                      enableSplit = true
                  }
              }
          }
          
          dependencies {
              implementation "com.facebook.react:react-android"
              implementation "com.facebook.react:hermes-android"
          }' > android/app/build.gradle
          
          echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.optibuy.collective">
              <uses-permission android:name="android.permission.INTERNET" />
              <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme">
                  <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>' > android/app/src/main/AndroidManifest.xml
          
          echo '<resources>
              <string name="app_name">OptiBuy</string>
          </resources>' > android/app/src/main/res/values/strings.xml
          
          echo '#!/usr/bin/env sh
          GRADLE_APP_NAME="Gradle"
          GRADLE_OPTS="-Dorg.gradle.appname=$GRADLE_APP_NAME"
          exec "/usr/bin/gradle" "$@"' > android/gradlew
          
          chmod +x android/gradlew
          
          echo "Android configuration completed"
          ls -la android/
          
      - name: Create Upload Keystore
        script: |
          echo "=== Creating Upload Keystore ==="
          cd OptiBuy
          
          keytool -genkeypair \
            -alias upload \
            -keyal
