# Original Successful 284-line Configuration with ANYQUE-style Managed Signing
# Based on proven 2.64 MB AAB generation with Google Play Console compatibility

workflows:
  minimal-aab:
    name: OptiBuy AAB Build - Google Play Managed Signing
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        PACKAGE_NAME: "com.optibuy.collective"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      node: 18
    
    scripts:
      - name: Setup and Create React App
        script: |
          echo "=== Creating minimal React project ==="
          
          # Create package.json
          cat > package.json << 'EOF'
          {
            "name": "optibuy",
            "version": "1.0.0",
            "scripts": {
              "build": "vite build"
            },
            "dependencies": {
              "react": "^18.2.0",
              "react-dom": "^18.2.0"
            },
            "devDependencies": {
              "vite": "^5.0.0",
              "@vitejs/plugin-react": "^4.0.0",
              "typescript": "^5.0.0",
              "tailwindcss": "^3.3.0",
              "autoprefixer": "^10.4.0",
              "postcss": "^8.4.0"
            }
          }
          EOF
          
          # Create directories
          mkdir -p src public
          
          # Create index.html
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>OptiBuy</title>
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="/src/main.jsx"></script>
            </body>
          </html>
          EOF
          
          # Create index.css with Tailwind
          cat > src/index.css << 'EOF'
          @tailwind base;
          @tailwind components;
          @tailwind utilities;
          EOF
          
          # Create App.jsx
          cat > src/App.jsx << 'EOF'
          import './index.css'
          
          function App() {
            return (
              <div className="p-5 text-center">
                <h1 className="text-2xl font-bold mb-4">OptiBuy - Collective Purchasing</h1>
                <p className="mb-4">Discover invisible buying neighbors for bulk discounts</p>
                <button 
                  className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
                  onClick={() => alert('Welcome to OptiBuy!')}
                >
                  Get Started
                </button>
              </div>
            )
          }
          export default App
          EOF
          
          # Create main.jsx
          cat > src/main.jsx << 'EOF'
          import React from 'react'
          import ReactDOM from 'react-dom/client'
          import App from './App'
          
          ReactDOM.createRoot(document.getElementById('root')).render(<App />)
          EOF
          
          # Create vite.config.js
          cat > vite.config.js << 'EOF'
          import { defineConfig } from 'vite'
          import react from '@vitejs/plugin-react'
          
          export default defineConfig({
            plugins: [react()],
            build: {
              outDir: 'dist'
            }
          })
          EOF
          
          # Create postcss.config.js
          cat > postcss.config.js << 'EOF'
          export default {
            plugins: {
              tailwindcss: {},
              autoprefixer: {},
            },
          }
          EOF
          
          # Create tailwind.config.js
          cat > tailwind.config.js << 'EOF'
          /** @type {import('tailwindcss').Config} */
          export default {
            content: [
              "./index.html",
              "./src/**/*.{js,ts,jsx,tsx}",
            ],
            theme: {
              extend: {},
            },
            plugins: [],
          }
          EOF
          
          # Create tsconfig.json for Capacitor
          cat > tsconfig.json << 'EOF'
          {
            "compilerOptions": {
              "target": "ES2020",
              "useDefineForClassFields": true,
              "lib": ["ES2020", "DOM", "DOM.Iterable"],
              "module": "ESNext",
              "skipLibCheck": true,
              "moduleResolution": "bundler",
              "allowImportingTsExtensions": true,
              "resolveJsonModule": true,
              "isolatedModules": true,
              "noEmit": true,
              "jsx": "react-jsx",
              "strict": true,
              "noUnusedLocals": true,
              "noUnusedParameters": true,
              "noFallthroughCasesInSwitch": true
            },
            "include": ["src"],
            "references": [{ "path": "./tsconfig.node.json" }]
          }
          EOF

      - name: Build and Setup Capacitor
        script: |
          echo "=== Installing dependencies ==="
          npm install
          
          echo "=== Building React app ==="
          npm run build
          ls -la dist/
          
          echo "=== Installing Capacitor (compatible version) ==="
          npm install @capacitor/core@5.7.8 @capacitor/cli@5.7.8 @capacitor/android@5.7.8
          
          echo "=== Initialize Capacitor ==="
          npx cap init OptiBuy com.optibuy.collective --web-dir=dist
          
          echo "=== Add Android platform ==="
          npx cap add android
          
          echo "=== Fix Java compatibility in all Gradle files ==="
          
          # Fix app build.gradle - replace existing compileOptions
          sed -i '/compileOptions/,/}/d' android/app/build.gradle || true
          cat >> android/app/build.gradle << 'EOF'

          android {
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
          }
          EOF
          
          # Fix project build.gradle
          sed -i 's/classpath.*com.android.tools.build:gradle.*/classpath "com.android.tools.build:gradle:8.5.2"/' android/build.gradle
          
          # Set global gradle properties for Java 17
          cat >> android/gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
          org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
          EOF
          
          echo "=== Create custom capacitor.config.ts with Java 17 ==="
          cat > capacitor.config.ts << 'EOF'
          import { CapacitorConfig } from '@capacitor/cli';

          const config: CapacitorConfig = {
            appId: 'com.optibuy.collective',
            appName: 'OptiBuy',
            webDir: 'dist',
            android: {
              buildOptions: {
                keystorePath: undefined,
                keystorePassword: undefined,
                keystoreAlias: undefined,
                keystoreAliasPassword: undefined,
                releaseType: 'AAB'
              }
            }
          };

          export default config;
          EOF
          
          echo "=== Sync web assets ==="
          npx cap sync android
          
          echo "=== Verify Java configuration fixes ==="
          echo "Checking all build.gradle files for Java version:"
          find android -name "build.gradle" -exec grep -l "JavaVersion\|sourceCompatibility\|targetCompatibility" {} \; | while read file; do
            echo "--- $file ---"
            grep -E "(JavaVersion|sourceCompatibility|targetCompatibility)" "$file" || true
          done

      - name: Configure ANYQUE-style release signing
        script: |
          cd android
          
          # Create a keystore for release signing like ANYQUE
          keytool -genkey -v -keystore release-key.keystore -alias release-key -keyalg RSA -keysize 2048 -validity 10000 -storepass optibuy123 -keypass optibuy123 -dname "CN=OptiBuy, OU=Mobile, O=OptiBuy, L=Istanbul, S=Istanbul, C=TR"
          
          # Configure release signing and R8 obfuscation in build.gradle like ANYQUE
          cat >> app/build.gradle << 'EOF'
          
          android {
              compileSdkVersion 34
              
              defaultConfig {
                  targetSdkVersion 34
                  minSdkVersion 21
              }
              
              signingConfigs {
                  release {
                      storeFile file('../release-key.keystore')
                      storePassword 'optibuy123'
                      keyAlias 'release-key'
                      keyPassword 'optibuy123'
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled true
                      shrinkResources true
                      debuggable false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }
          EOF
          
          # Create proguard rules file like ANYQUE
          cat > app/proguard-rules.pro << 'EOF'
          # Keep main activity
          -keep public class * extends android.app.Activity
          -keep public class * extends android.app.Application
          -keep public class * extends android.app.Service
          
          # Keep Capacitor classes
          -keep class io.ionic.capacitor.** { *; }
          
          # Reduce warnings
          -dontwarn java.lang.invoke.StringConcatFactory
          EOF

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build AAB like ANYQUE
        script: |
          cd android
          
          # Set Java version explicitly
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          
          echo "=== Update gradle wrapper ==="
          # Update gradle wrapper to use compatible version
          sed -i 's/gradle-.*-all.zip/gradle-8.9-all.zip/g' gradle/wrapper/gradle-wrapper.properties
          cat gradle/wrapper/gradle-wrapper.properties
          
          chmod +x gradlew
          echo "Building properly signed release bundle..."
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon --stacktrace
          
          echo "Build completed. Checking output..."
          ls -la app/build/outputs/bundle/release/
          file app/build/outputs/bundle/release/app-release.aab
          echo "Bundle file size: $(du -h app/build/outputs/bundle/release/app-release.aab)"
          
          echo "Copying bundle for artifacts..."
          cp app/build/outputs/bundle/release/app-release.aab ../optibuy-managed-v1.0.0.aab
          ls -la ../optibuy-managed-v1.0.0.aab
          file ../optibuy-managed-v1.0.0.aab

    artifacts:
      - optibuy-managed-v1.0.0.aab
      - android/release-key.keystore
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
