workflows:
  optibuy:
    name: OptiBuy - Permanent Keystore Build
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.optibuy.collective"
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
        ANDROID_HOME: /usr/local/share/android-sdk
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        KEYSTORE_PASSWORD: "OptiBuy2025Secure"
        KEY_ALIAS: "upload"
        KEY_PASSWORD: "OptiBuy2025Secure"
    scripts:
      - name: Create Minimal Android Project
        script: |
          echo "=== Creating Minimal Android Project ==="
          
          mkdir -p OptiBuy/android/app/src/main/java/com/optibuy/collective
          mkdir -p OptiBuy/android/app/src/main/res/values
          mkdir -p OptiBuy/android/app/src/main/res/layout
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-hdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-mdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xhdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xxhdpi
          mkdir -p OptiBuy/android/app/src/main/res/mipmap-xxxhdpi
          mkdir -p OptiBuy/android/gradle/wrapper
          
          cd OptiBuy
          
          echo "Creating gradle wrapper properties..."
          cat > android/gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          echo "Creating gradle.properties..."
          cat > android/gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.enableJetifier=true
          android.bundle.enableUncompressedNativeLibs=false
          android.enableR8.fullMode=true
          org.gradle.parallel=true
          org.gradle.configureondemand=true
          org.gradle.daemon=true
          EOF
          
          echo "Creating settings.gradle..."
          cat > android/settings.gradle << 'EOF'
          rootProject.name = 'OptiBuy'
          include ':app'
          project(':app').projectDir = new File(rootProject.projectDir, 'app')
          EOF
          
          echo "Creating root build.gradle..."
          cat > android/build.gradle << 'EOF'
          buildscript {
              ext {
                  buildToolsVersion = "34.0.0"
                  minSdkVersion = 21
                  compileSdkVersion = 35
                  targetSdkVersion = 35
              }
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.1.4'
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          EOF
          
          echo "Creating app build.gradle..."
          cat > android/app/build.gradle << 'EOF'
          apply plugin: 'com.android.application'
          
          android {
              namespace 'com.optibuy.collective'
              compileSdkVersion rootProject.ext.compileSdkVersion
              buildToolsVersion rootProject.ext.buildToolsVersion
              
              defaultConfig {
                  applicationId "com.optibuy.collective"
                  minSdkVersion rootProject.ext.minSdkVersion
                  targetSdkVersion rootProject.ext.targetSdkVersion
                  versionCode 4
                  versionName "1.4.0"
              }
              
              signingConfigs {
                  release {
                      storeFile file('optibuy-permanent-upload.jks')
                      storePassword System.getenv("KEYSTORE_PASSWORD") ?: "OptiBuy2025Secure"
                      keyAlias System.getenv("KEY_ALIAS") ?: "upload"
                      keyPassword System.getenv("KEY_PASSWORD") ?: "OptiBuy2025Secure"
                  }
              }
              
              buildTypes {
                  release {
                      minifyEnabled true
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                      signingConfig signingConfigs.release
                  }
              }
              
              bundle {
                  language {
                      enableSplit = false
                  }
                  density {
                      enableSplit = true
                  }
                  abi {
                      enableSplit = true
                  }
              }
          }
          
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
              implementation 'com.google.android.material:material:1.9.0'
          }
          EOF
          
          echo "Creating AndroidManifest.xml..."
          cat > android/app/src/main/AndroidManifest.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:label="@string/app_name"
                  android:theme="@style/AppTheme">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          
          echo "Project structure created successfully"
          
      - name: Create Permanent Keystore from Base64
        script: |
          echo "=== Creating Permanent Keystore ==="
          cd OptiBuy
          
          # Decode the permanent keystore from base64
          echo 'MIIKxAIBAzCCCm4GCSqGSIb3DQEHAaCCCl8EggpbMIIKVzCCBa4GCSqGSIb3DQEHAaCCBZ8EggWbMIIFlzCCBZMGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFM6Cq9uWv86kIQYzUEsozCA7RluHAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQPmKS1MHUgWSML2V/jFZ3ogSCBNCOU1qj2UMpXs4XEvY1Nj057KL8AuKpBnQlwrmNcmHWVUUXj8EjK6oldPPN1fMNPQoQvp4rrkR+ZCNaXSX3Ym3uivJGjWj0Tlqlh9E54MuwCmBTk9MRcH4pXmEnQNBVfiIk3vZSe8IKq4FsOVAaLojtzpwU45SLzWS+ep/t52HpMeZ+Fbeb8bSSZsQk/wr38Jf/txAQwGa9ZYqT6MgjFpv4t/UppOH8UkdefDvp8uGV+3Fz9pidT2KqbQJfXsXjqmRED9Kg8dpUtaqFgfD/apcJlYxaCz9CJeyva3vIHR5Cy9i/ECgXN/gbiHmGlw6GFl1uhypgP9rHn717W1W8++TfFEIfD2PJnK7le1MCTbztqUmvfzinkEa7qzHb/y3fwVcaydfnmhXoKWsuGxWrzrRSHU0/sKP97U4bDiNE4e4nduxQr2qstIxKE7yf3Iq3gPpqqDoSoPnBH7aPZf3k3OybOtacbZUwUU+A3hxL+Iix9D7EKWHDstOTbUlQIaOZr9Znw0Xm0GNy/VSwl2lg7GP5n1NHiY1iLC5dIJ5BWorNcsyg3FKA4eLgKXr53wTmHe2wTg/Pz43rO5zcIPag1Fzu5aQM7vF8KBpA2D4gWMCEYHppL3R03tOKIQ5upQrNETz9TBpJy/akaK1qb6P6Qd5uAqCVjbL7Qk+zgjbO3T/ZGqOMOkf7kLr+AImc1GM3pS7kgsXblOIDjFAJGRL0U6ofpkGCuMAFmPRAgQkAs8+6iTTpZTX3fNmYeTO9DA0XaSLd8qmD9wBJKYIK/3QVO30xDXk0QB2JlncnzAwlM+0vckhusLo3jM4NXi9LBRgRry/15QOnHxP/va7kcTgLoFMcyWsZrOuYfI2vO5zCKeRRwrKDITWUA3guQvwnDd7MOn4EKLtkeQQpZxDRMyHQpei07LoGfrkCVMT0BM7pPxL4LRNtsyAoGTGbCwbo02asxwsXyodOWUmw6ND4GZit4FtlwRk5atdjL5S252GUauS0YUwpd75kDOgsuEEB3I/4/6tMTcBUxjscAqB+QX25jIF8BPA0OBIZTeRaxTz4SKxLCXYW7RckaofgsXlThCebzUPB4Ve4c/qzUvOlgMm8oe2m69t8SFmiiBFFwhM9YzPi2CB0FLQN8lIlz1VJIzb1saLR7TYza4M6H7adDX6P7rFIWPgdGjMKCgv11xIXbHv5ALZ7wP8LIYqmmTRK/V4tafin813MscxTJkxRIFD0RuCLkREZOMlIOsGMtRJKXNHIs3RpaPZ/eGCKyFBeR7Vb098lu4vW++6bRHKXqSXa/DLX1Vuwj5beBA2b43gjXttFAFpg+/pv3kskKBuVdXC+j1BM6EzmtMinByGnlGmzKdtubxvn4kNkSOCimNEKeqkJpDaO5JcziJaJ7/gttdv2s+IZ6OCajgFuUTmLqCzy8Pjz3NXGP6rmFpdJDlpRA1XjtQJaYlEceJ23kisPV1fEiXmDMIoHkAbQIHu5w7JIKEwradNYkAxmNOT+BbcUBFgVHgkDeQDnCk5mpq34bkLfud1bbWZvswMDUX81renisymZZ16a1HxZeaVKm5Q8AdJNVh7fBePQNE7TnZEtYVMWiWaJ0r2lkY2PK93+uIMk/ioP93UbkFZ2NYkwLSrtu27/ADFAMBsGCSqGSIb3DQEJFDEOHgwAdQBwAGwAbwBhAGQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc2NjA1NjA1OTMxOTCCBKEGCSqGSIb3DQEHBqCCBJIwggSOAgEAMIIEhwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTvEJ47wJN9l0ZMLkxjB1uNShal1wICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEECDumKbd7fxlfoSa4e8CeQaAggQQZ69u4NzrruOrd3nRlV1V0gnk7BMmH/caQCCC5sWjK0RMutIcysoJRK97GKTZJxiUegu5tJKME/D+t4dQaJCvvYK2B9xRczVUtga9VFwPzHUQ/m6sboRrhTE0TH0O+i0yN/rTX/jkjs9jmoPWvHQxux9+7HppOho+v0B4UUvIA9iY5uj8fw+Wafzh87e6L44n/++UfxU1W2bZMPFuHG8un6WA7dcTK866CLekZeT0L0nCHPqemDjQqnib6n0WX3fDhofp3PaRyoT9MgTscQcwbBFpRrbm7bq/y41+LWhu85NWWpv3b/1HPkCgkH5yQBA8U6lSpPenfemqI+lwq+Q8zZiXvhDmQZ6ykDWQuL0VkNc03DaltmkkCM6QRtGpg24gCefQKEaLG8M5/rWxXO6YJXfqzCGCq80vm2brGzGlYCwhClJ/LOXSlHDjqEk9OPumt1mJTSAco+WrcG2G+g8DijFbAgm7lycHVW0dx/GkoOb5y24fUdoaO2JrLG0/mBhFhY7xntszXBSFIqX6bGe4xYX1dx7YpM3IMOZBFonX1xLwqRPOe7m26Xc79ljO9e3vCNxfRMxhU/CA1kro3cBkUuKuRhu8JrWuzWJwaeGJfpuIBg11AuKq7/XEOTtIdwKu8IKDTU0Dt5S9a/a6DDb/1ThI07rqeXnpSesUBHCgNOXK9EGgCH0PqeDKwTubIOY3sf7k+3BeS+duglN6c47DWbow9twPeSvnLcDmh2VylAMM25c25u2YubenusyPUdXJ+/uhdx2OA0i0CK8mS3Ha8MfPmGPZ8CJQrPvF5lX2x01PqHY6ot6Jx7yHapNmbbWxm4uZc6h8MMbneyNIupgkAvOdU/8aG1Dlm9Mo5+58i4BQvoSa8E/A7cCpWQWBcnIwIyTtQlaBvZ+5Hf410Bhlv1OmWtFy2N67A7mfATTVYPpJ2TITzxPQEdZmxEE6vR+KCwYw4OYam+JTyxC16BmlsTFDoVt3nGyt2bO5UyfqlRNdtyeMe4qG5ykxySFvu5n4TsVO0L3ujEwymMptrdEGURGn/5FdKhWdnxFH7Y86A69WMMfLDEoGya3lxUx+l8Cf1SHtdj5ZZOwyhGwM9+9M9J+O0ipUY+ETyKXwB4VWQenewOezy0+OmUYjtg3hkoCTRHC8XRZ19CNPm2EsqLw2uA7gQJ+31moSjzDYX/wDs4Au4gDqFT5besdMrEn63leS5mtCYRCyWFr/6tZp5DKE1Jli3DfeGcE57M2PLSt6L53Zel6Ugiea8T1j/MAvNT02FNJDLT9rZ4uTXXXuvPUusBiY7M/ZJq+ZABpRC0Ibkroghldw3l4Eaut1NKthSLrcEn/CIukWn7g+xOAX/GtzMX1N53RKfNwtP3UMCZ6UwbUwTTAxMA0GCWCGSAFlAwQCAQUABCCx9WONsxjoSt1xlFCRVOk0cIK4H552BSN71KZC8HL4YwQUUTrKonhdbnR4Hc9NUHDoIX9kg+ICAicQ' | base64 -d > android/app/optibuy-permanent-upload.jks
          
          echo "Keystore created. Verifying fingerprint..."
          keytool -list -v -keystore android/app/optibuy-permanent-upload.jks -storepass OptiBuy2025Secure -alias upload | grep "SHA1"
          
          # Export PEM certificate for Google Play
          keytool -export -rfc -alias upload -file optibuy-upload-certificate.pem -keystore android/app/optibuy-permanent-upload.jks -storepass OptiBuy2025Secure
          echo "PEM certificate exported for Google Play Console upload"
          
      - name: Create Android Resources and Code
        script: |
          echo "=== Creating Android Resources and Code ==="
          cd OptiBuy
          
          echo "Creating strings.xml..."
          cat > android/app/src/main/res/values/strings.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">OptiBuy</string>
              <string name="welcome_title">OptiBuy</string>
              <string name="welcome_subtitle">Collective Purchasing Platform</string>
              <string name="welcome_description">Ready for Google Play Store deployment</string>
          </resources>
          EOF
          
          echo "Creating styles.xml..."
          cat > android/app/src/main/res/values/styles.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
                  <item name="colorPrimary">#4285F4</item>
                  <item name="colorPrimaryDark">#3367D6</item>
                  <item name="colorAccent">#34A853</item>
              </style>
          </resources>
          EOF
          
          echo "Creating activity_main.xml layout..."
          cat > android/app/src/main/res/layout/activity_main.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="#f8f9fa">
          
              <TextView
                  android:id="@+id/title"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="@string/welcome_title"
                  android:textSize="32sp"
                  android:textStyle="bold"
                  android:textColor="#000000"
                  android:layout_marginBottom="10dp"
                  app:layout_constraintTop_toTopOf="parent"
                  app:layout_constraintBottom_toBottomOf="parent"
                  app:layout_constraintLeft_toLeftOf="parent"
                  app:layout_constraintRight_toRightOf="parent"
                  app:layout_constraintVertical_chainStyle="packed" />
          
              <TextView
                  android:id="@+id/subtitle"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="@string/welcome_subtitle"
                  android:textSize="18sp"
                  android:textColor="#666666"
                  android:layout_marginBottom="20dp"
                  app:layout_constraintTop_toBottomOf="@id/title"
                  app:layout_constraintLeft_toLeftOf="parent"
                  app:layout_constraintRight_toRightOf="parent" />
          
              <TextView
                  android:id="@+id/description"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="@string/welcome_description"
                  android:textSize="16sp"
                  android:textColor="#4285F4"
                  android:textStyle="bold"
                  app:layout_constraintTop_toBottomOf="@id/subtitle"
                  app:layout_constraintLeft_toLeftOf="parent"
                  app:layout_constraintRight_toRightOf="parent" />
          
          </androidx.constraintlayout.widget.ConstraintLayout>
          EOF
          
          echo "Creating MainActivity.java..."
          cat > android/app/src/main/java/com/optibuy/collective/MainActivity.java << 'EOF'
          package com.optibuy.collective;
          
          import androidx.appcompat.app.AppCompatActivity;
          import android.os.Bundle;
          
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  setContentView(R.layout.activity_main);
              }
          }
          EOF
          
          echo "Creating proguard-rules.pro..."
          cat > android/app/proguard-rules.pro << 'EOF'
          # Add project specific ProGuard rules here.
          -keep class com.optibuy.collective.** { *; }
          -dontwarn okio.**
          -dontwarn retrofit2.**
          EOF
          
          echo "Downloading and creating app icons..."
          # Download the actual OptiBuy logo from the deployed app
          curl -L -o icon_original.png "https://opti-buy-tracker-metealper.replit.app/app-icon.png"
          
          # Verify download
          if [ -f "icon_original.png" ]; then
            echo "Icon downloaded successfully"
            file icon_original.png
            
            # Resize to all Android mipmap sizes using sips (macOS)
            sips -z 48 48 icon_original.png --out android/app/src/main/res/mipmap-mdpi/ic_launcher.png
            sips -z 72 72 icon_original.png --out android/app/src/main/res/mipmap-hdpi/ic_launcher.png
            sips -z 96 96 icon_original.png --out android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
            sips -z 144 144 icon_original.png --out android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            sips -z 192 192 icon_original.png --out android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
            
            # Create round icons (same as regular for now)
            cp android/app/src/main/res/mipmap-mdpi/ic_launcher.png android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
            cp android/app/src/main/res/mipmap-hdpi/ic_launcher.png android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
            cp android/app/src/main/res/mipmap-xhdpi/ic_launcher.png android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
            cp android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
            cp android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
            
            echo "App icons created at all densities"
            ls -la android/app/src/main/res/mipmap-*/ic_launcher*.png
          else
            echo "ERROR: Failed to download icon"
            exit 1
          fi
          
          echo "Android resources and code created successfully"
          
      - name: Build AAB with System Gradle
        script: |
          echo "=== Building AAB for Google Play Console ==="
          cd OptiBuy/android
          
          echo "Using system gradle directly..."
          which gradle
          gradle --version
          
          echo "Running gradle clean..."
          gradle clean
          
          echo "Building AAB bundle..."
          gradle bundleRelease
          
          echo "=== AAB Build Verification ==="
          find . -name "*.aab" -type f
          ls -la app/build/outputs/bundle/release/ || echo "Release directory not found"
          
          if [ -f "app/build/outputs/bundle/release/app-release.aab" ]; then
              echo "AAB file created successfully"
              file app/build/outputs/bundle/release/app-release.aab
              
              cd ../..
              cp OptiBuy/android/app/build/outputs/bundle/release/app-release.aab ./optibuy-google-play-ready.aab
              cp OptiBuy/android/app/build/outputs/bundle/release/app-release.aab ./optibuy-$(date +%Y%m%d-%H%M).aab
              
              echo "=== GOOGLE PLAY CONSOLE UPLOAD READY ===" > google_play_deployment.txt
              echo "Package: com.optibuy.collective" >> google_play_deployment.txt
              echo "Version Code: 4" >> google_play_deployment.txt
              echo "Version Name: 1.4.0" >> google_play_deployment.txt
              echo "Upload Key SHA-1: B4:D4:43:DA:BC:58:75:01:08:34:68:0B:58:4C:AA:58:58:27:D1:1F" >> google_play_deployment.txt
              echo "Target SDK: 35 (Android 15)" >> google_play_deployment.txt
              echo "Status: Ready for Google Play Console Upload" >> google_play_deployment.txt
              
              echo "AAB generation completed successfully!"
              ls -la *.aab
          else
              echo "ERROR: AAB file not generated"
              echo "Checking all build outputs:"
              find OptiBuy/android -name "*.aab" -type f
              exit 1
          fi
          
    artifacts:
      - "*.aab"
      - "OptiBuy/android/app/build/outputs/bundle/release/app-release.aab"
      - "OptiBuy/optibuy-upload-certificate.pem"
      - "google_play_deployment.txt"
    publishing:
      email:
        recipients:
          - build@optibuy.com
        notify:
          success: true
          failure: true
